export default {
  locale: "en-GB",
  "zoom.in": "Zoom in",
  "zoom.out": "Zoom out",
  "zoom.reset": "Reset view",
  "zoom.hint": "Zoom in to see the details",
  "zoom.pan": "Scroll to explore the enlarged view",
  "zoom.range": "Visible interval",
  "zoom.rangeHint": "Move the interval with the slider",
  "error.title": "This page didn't load",
  "error.description": "Something went wrong. Try again or go back home.",
  "error.retry": "Try again",
  "error.home": "Go home",
  "error.notFound": "Page not found",
  "error.notFoundDescription":
    "The page you're looking for doesn't exist or has been moved.",
  "nav.home": "Home",
  "nav.mappa": "Map",
  "nav.impatto": "Impact",
  "nav.storia": "Story",
  "nav.demo": "Demo",
  "nav.menu": "Open menu",
  "nav.lang": "Language",
  "copy.description":
    "Giano reconstructs missing weather data using nearby measurements in time and space. Explore 497 series from 171 Meteotrentino stations processed by the model.",
  "copy.results":
    "To evaluate Giano, we hid some measurements and compared the reconstructions with the originals. These results average 13 tests, each repeated with five random seeds over the validation period.",
  "copy.example":
    "Each example contains 72 hourly observations, some hidden for the test. The chart brings together the visible inputs, hidden measurements and reconstruction.",
  "copy.noValidation": "No evaluation results are available for this variable.",
  "var.temperature": "Temperature",
  "var.precipitation": "Precipitation",
  "var.humidity": "Humidity",
  "var.pressure": "Pressure",
  "var.wind_speed": "Wind speed",
  "var.wind_direction": "Wind direction",
  "home.badge": "WebValley 2025 · Meteotrentino",
  "home.subtitle": "Reconstruction of weather observations",
  "home.ctaMap": "Explore the {n} stations",
  "home.ctaDemo": "Watch the demo",
  "home.heroAlt":
    "The mountains of Trentino at sunset with a network of weather stations",
  "home.stat1": "Stations with processed histories",
  "home.stat2": "Processed station–variable series",
  "home.stat3": "Missing hourly values reconstructed",
  "home.stat4": "Stations evaluated on hidden measurements",
  "home.errorTitle": "How close is the reconstruction?",
  "home.errorNote":
    "MAE is the mean absolute error. RMSE is the average of the individual case/seed RMSEs. Each variable keeps its own unit.",
  "home.coverTitle": "Network coverage",
  "home.coverNote":
    "Stations with data, examples and evaluation results. A station can belong to more than one group.",
  "home.cover.catalog": "Catalogue",
  "home.cover.history": "History",
  "home.cover.examples": "Examples",
  "home.cover.validation": "Validation",
  "home.cover.series": "Stations",
  "home.measuredTitle": "From measurement to reconstruction",
  "home.validationSet": "Validation · {n} test and random-seed combinations",
  "home.seeds": "Random seeds: {v}",
  "home.source": "Data source: {v}",
  "home.networkTitle": "The network in Trentino",
  "home.openMap": "Open the map",
  "map.title": "Station map",
  "map.filter.all": "All stations ({n})",
  "map.filter.history": "Processed history ({n})",
  "map.filter.validation": "Evaluation available ({n})",
  "map.filter.examples": "With examples ({n})",
  "map.search": "Search station",
  "map.overlapNote": "Choose a station on the map or in the list.",
  "map.listTitle": "Station list",
  "map.listHint": "{n} stations · select a name to see its data",
  "map.selectedStation": "Selected station",
  "map.availability": "Station data",
  "map.variableLabel": "Variable shown in the chart",
  "map.tag.validation": "evaluation available",
  "map.tag.history": "history available",
  "map.tag.catalog": "catalogue only",
  "map.empty": "No stations",
  "map.close": "Close",
  "map.noElevation": "Elevation not available",
  "map.elevation": "{v} m a.s.l.",
  "map.from": "From {v}",
  "map.to": " to {v}",
  "map.active": " · no closing date reported",
  "map.badge.history": "Historical series",
  "map.badge.validation": "Evaluation",
  "map.badge.examples": "Reconstruction example",
  "map.available": "Available",
  "map.unavailable": "Not available",
  "map.historyTitle": "History",
  "map.period": "From {a} to {b}",
  "map.noPeriod": "Period not available",
  "map.observedHours": "Observed hours",
  "map.missingHours": "Missing hours",
  "map.validationTitle": "Station evaluation",
  "map.groups": "Groups",
  "map.exampleTitle": "Illustrative example",
  "map.exampleYes":
    "Available: 72 hours of data with a test gap and Giano's reconstruction.",
  "map.exampleNo": "No illustrative example for this variable.",
  "map.catalogOnly":
    "This station is in the Meteotrentino catalogue, but we have no series to display.",
  "map.sourceLabel": "Source: {v}",
  "map.selectHint": "Select a station on the map",
  "map.ariaBoundary":
    "Geographic boundary of the Autonomous Province of Trento",
  "map.stationsCount": "{n} stations · Meteotrentino",
  "map.legend.giano": "history processed with Giano",
  "map.legend.local": "ring: evaluation available",
  "map.legend.catalog": "catalogue only",
  "map.legend.boundary": "Boundary: © OpenStreetMap contributors",
  "impact.title": "Impact",
  "impact.intro":
    "When a station stops recording, it leaves a gap in the record. Giano uses the available data to reconstruct it.",
  "impact.h1": "Why Giano is needed",
  "impact.p1":
    "Faults and maintenance can interrupt measurements. Giano reconstructs missing values using station observations and, where available, ERA5 reanalysis data, without changing existing data.",
  "impact.c1t": "Climate trends",
  "impact.c1d": "Analysing long-term meteorological series",
  "impact.c2t": "Water resources",
  "impact.c2d":
    "Supporting analyses of precipitation and the hydrological cycle",
  "impact.c3t": "Alpine monitoring",
  "impact.c3d":
    "Reconstructing missing observations from high-altitude stations",
  "impact.statHistory":
    "stations processed out of {total} in the Meteotrentino catalogue, for a total of {series} station–variable series and {hours} missing hourly values reconstructed.",
  "impact.statExamples":
    "examples across {n} stations: 72-hour windows with hidden data to compare reconstructions with real measurements.",
  "impact.h2": "Why missing data matters",
  "impact.p2":
    "Not all gaps matter in the same way. Losing an hour on a stable day is different from losing the peak of a storm or several consecutive hours of temperature and humidity.",
  "impact.l1Lead": "Averages and comparisons can change",
  "impact.l1": "when missing data is concentrated in a specific period.",
  "impact.l2Lead": "An event may be only partly described",
  "impact.l2": "if the station stops recording at its most significant moment.",
  "impact.l3Lead": "Later analyses can be affected",
  "impact.l3":
    "when they use an incomplete series, for example in agriculture, water-resource management or forecasting models.",
  "impact.l4Lead": "Measurements and estimates remain distinct:",
  "impact.l4":
    "our charts always show observed data, reconstructions and remaining gaps.",
  "story.title": "How Giano began",
  "story.intro":
    "Giano began at WebValley 2025, Fondazione Bruno Kessler's research summer school. We started with a question from Meteotrentino: how can we recover the observations missing from weather-station records?",
  "story.genesis": "Three weeks at WebValley",
  "story.g1":
    "From 15 June to 5 July 2025, WebValley brought together Italian and international students to work on meteorology and data science. Through classes and group work, we learned to read real datasets, build models and discuss our results with researchers and tutors.",
  "story.g2":
    "Ours was Challenge 1, dedicated to reconstructing Meteotrentino's historical series. Before working on the model, however, we first had to understand the data properly, interpret its measurements, identify invalid values and align stations with different sampling frequencies.",
  "story.videoTitle": "WebValley 2025 presentation",
  "story.videoCaption":
    "The final presentation at Fondazione Bruno Kessler on 4th July 2025.",
  "story.team": "The team and our support",
  "story.member": "Team Giano · WebValley 2025",
  "story.tutor": "WebValley 2025 · our main tutor",
  "role.Data & Modeling": "Data & Modeling",
  "role.Machine Learning": "Machine Learning",
  "role.Analisi Climatica": "Climate Analysis",
  "role.Pipeline & Backend": "Pipeline & Backend",
  "role.Visualizzazione Dati": "Data Visualisation",
  "demo.title": "Model demo",
  "demo.intro":
    "An animation showing how Giano reconstructs an incomplete time series with support from ERA5-Land.",
  "demo.step1": "Reading the station's historical series",
  "demo.step2": "Time alignment with ERA5-Land",
  "demo.step3": "Detection of temporal gaps",
  "demo.step4": "Reconstruction with Giano",
  "demo.step5": "Completed series",
  "demo.pause": "Pause",
  "demo.play": "Play",
  "demo.restart": "Restart",
  "demo.step": "Step {i}/{n} · {label}",
  "demo.observed": "Observed",
  "demo.reconstructed": "Reconstructed by Giano",
  "demo.openTitle": "The code is open source",
  "demo.openText":
    "Notebooks, training pipeline and evaluation of the Giano model.",
  "demo.repo": "View the repository",
  "footer.text":
    "A project started at FBK WebValley 2025, working with Meteotrentino station data.",
  "footer.badge": "Project for Premio GF Marilli 2026",
  "footer.copy":
    "© {year} Team Giano · Data: Provincia autonoma di Trento — Meteotrentino",
  "nav.guida": "Use Giano",
  "site.skip": "Skip to content",
  "data.loading": "Loading data…",
  "data.error": "Could not load the data.",
  "data.retry": "Retry",
  "data.download": "Download JSON data",
  "chart.example": "Reconstruction example",
  "chart.history": "Historical series",
  "chart.visible": "Visible measurements",
  "chart.hidden": "Hidden measurements",
  "chart.reconstruction": "Giano reconstruction",
  "chart.showTruth": "Show hidden measurements",
  "chart.showReconstruction": "Show Giano reconstruction",
  "chart.showEra5": "Show ERA5-Land",
  "chart.era5Note":
    "ERA5-Land grid signal associated with the station, not a local measurement.",
  "map.legendTitle": "Map legend",
  "chart.exampleNote":
    "Some measurements were hidden to test the model. The chart compares the real values with the reconstructions.",
  "chart.exampleStats":
    "{hours} hourly points · {hidden} hidden · MAE {mae} · RMSE {rmse}",
  "chart.noExample":
    "There is no example for this series. You can explore its history.",
  "chart.noHistory": "No history is available for this series.",
  "history.note":
    "Observed data and Giano reconstructions, shown as dashed lines. Breaks in the chart are gaps that remain unfilled.",
  "history.observed": "Observed hours",
  "history.reconstructed": "Reconstructed hours",
  "history.unfilled": "Hours still missing",
  "history.overview": "Full history, month by month",
  "history.overviewNote":
    "Observed, reconstructed and missing hours per month. Select a month to see the hourly data.",
  "history.month": "Go to month",
  "history.start": "Starting date",
  "history.duration": "Range",
  "history.days": "{n} days",
  "history.previous": "Previous period",
  "history.next": "Next period",
  "history.values": "Hourly values",
  "history.empty": "No points available in this range.",
  "history.fullRange": "Archive: {start} — {end}",
  "map.resultNote":
    "Errors on observations hidden for validation: {groups} of {expected} test combinations evaluated.",
  "guide.title": "Use Giano",
  "guide.intro":
    "To reconstruct your own data, download Giano and run it in Python. Here is how to get started.",
  "guide.installTitle": "1. Set up the environment",
  "guide.installText":
    "Install Git and uv, then clone the repository and create the Python 3.11 environment. Run the commands below in a terminal.",
  "guide.weightsTitle": "2. Add data and weights",
  "guide.weightsText":
    "Download the dataset from Google Drive and keep its directory structure under data/. Trained weights go separately under checkpoints/; the wiki describes the paths and reproduction package.",
  "guide.runTitle": "3. Reconstruct a variable",
  "guide.runText":
    "This command uses the trained temperature model and saves the reconstruction to new NetCDF files. It preserves original observations and leaves gaps empty where context is insufficient.",
  "guide.commandNote":
    "Use giano-impute for inference. The giano command instead starts the preparation and training pipeline.",
  "guide.datasetTitle": "Data from another network",
  "guide.datasetText":
    "You need observations, station coordinates and a YAML configuration describing columns, units, time zone and quality codes. The importer creates the common format; model accuracy then needs evaluating on the new data.",
  "guide.exampleText": "examples/datasets shows how to organise the files.",
  "guide.contextTitle": "What do the 72 hours mean?",
  "guide.contextText":
    "Giano reads 72 hours at a time, moving the window along the record. Some measurements must be available to reconstruct the missing ones. The notebooks show the process on real examples.",
  "guide.wiki": "Full guide in the wiki",
  "guide.release": "Data, weights and reproduction",
  "guide.dataset": "External dataset guide",
  "guide.notebooks": "Open the notebooks",
  "guide.copy": "Copy command",
  "guide.copied": "Copied",
  "guide.copyFailed": "Select and copy the command below.",
  "story.prototypeTitle": "The first Giano",
  "story.prototype1":
    "The prototype worked with temperature and wind speed. Alongside station measurements, it used ERA5-Land, a reanalysis describing weather patterns on a grid. A bidirectional LSTM read each sequence both ways, using the context before and after a gap.",
  "story.prototype2":
    "To measure reconstruction quality, we hid observations we already knew and compared the model's answer with the original values. The name Giano, Italian for Janus, reflects this two-way view: like the Roman god's two faces, the model looks in both directions. We presented the work on 4th July 2025.",
  "story.evolutionTitle": "After the summer school",
  "story.evolution1":
    "We kept working on the project after WebValley. Moving to ImputeFormer let us study temporal context and relationships between stations together. Precipitation, humidity, pressure and wind direction joined the original two variables.",
  "story.evolution2":
    "The current model starts from interpolation and learns a correction for longer gaps. Around it, we built data preparation, training and comparisons with simpler methods. These checks also led us to correct the data filtering and training objective before repeating the experiments.",
  "story.releaseTitle": "From experiments to a usable project",
  "story.release1":
    "The comparison now covers six variables, five seeds and 13 gap scenarios. We added an experiment on subsequent forecasts, support for importing other datasets and an initial test on Swiss stations. The notebooks and wiki follow the work from data to results.",
  "story.release2":
    "This website offers another way to explore the work. It lets you choose a station, inspect a reconstruction and browse its history. You can also run the code yourself, independently of the site.",
  "story.sources": "Sources and further reading",
  "story.sourceSchool": "The WebValley 2025 challenge",
  "story.sourceMagazine": "The story in FBK Magazine",
  "story.tutorNote":
    "Rishabh worked most closely with us on the project, alongside the school's other tutors.",
  "story.tutorList": "Full tutor list",
  "story.thanksTitle": "Thank you",
  "story.thanksData":
    "To Meteotrentino for the station data and for giving us a real problem to work on.",
  "story.thanksSchool":
    "To Fondazione Bruno Kessler for the WebValley experience, and to the researchers and tutors who supported us. The time and knowledge they shared helped get this project started.",
  "impact.downstreamTitle": "Can better reconstruction help a later forecast?",
  "impact.downstreamIntro":
    "We tested this in a downstream experiment: a subsequent use of the data. We took one small forecasting model, trained on complete histories, and gave it a damaged series followed by the same series repaired by Giano. The forecaster stays the same, only its input history changes.",
  "impact.downstreamProtocol":
    "The forecasts cover the next 1, 6, 12 and 24 hours. Giano sees only the history available at the forecast time, without access to future values.",
  "impact.downstreamCaption":
    "Forecast error (MAE) · mean over five seeds, four gap types and four forecast horizons",
  "impact.downstreamVariable": "Variable and station",
  "impact.downstreamDamaged": "Damaged history",
  "impact.downstreamRepaired": "Repaired history",
  "impact.downstreamReduction": "Error reduction",
  "impact.downstreamBaseline":
    "In the damaged history, missing values are replaced with a neutral value: the median.",
  "impact.downstreamConclusion":
    "Temperature, humidity and pressure improve in this test. Precipitation gets slightly worse and wind direction changes little. These results cover one station per variable.",
  "impact.downstreamLink": "Full method and results",
  "impact.useTitle": "Use Giano with your own data",
  "impact.useText":
    "The project goes beyond the stations on the map. You can run Giano on your computer, use the released weights or train new models. To import another network, provide CSV observations, station coordinates and a file describing their format.",
  "impact.useDetail":
    "The guide takes you from installation to your first reconstruction.",
  "impact.useGuide": "How to use Giano",
  "impact.useCode": "Browse the code",
  "demo.era5": "ERA5-Land · supporting signal",
  "demo.alignedHour": "Same hour",
  "demo.alignmentNote":
    "The dotted curve shows ERA5-Land aligned with the station's hourly timeline. It provides context even where local measurements are missing, but its grid cannot capture every detail of the terrain and local microclimate: it does not replace station observations.",
  "guide.downloadData": "Dataset on Google Drive",
};
